// <auto-generated />
namespace InterventionWebSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Insertingdata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Insertingdata));
        
        string IMigrationMetadata.Id
        {
            get { return "201907290933531_Inserting data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
