// <auto-generated />
namespace InterventionWebSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update9));
        
        string IMigrationMetadata.Id
        {
            get { return "201909022359296_update9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
